name: Maven CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 21
      uses: actions/setup-java@v1
      with:
        java-version: 21

    - name: Build project with Maven
      run: mvn -B compile --file pom.xml

    - name: Build project with Maven
      run: mvn -B package --file pom.xml

    - uses: actions/upload-artifact@v4
      with:
        name: pingbriel-built-gh-actions.jar
        path: ./target/Pingbriel-1.0-SNAPSHOT.jar
